# This file was generated by GoReleaser. DO NOT EDIT.
cask "fr8" do
  name "fr8"
  desc "Manage git worktrees as isolated dev workspaces"
  homepage "https://github.com/protocollar/fr8"
  version "0.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fr8"

  on_macos do
    on_intel do
      url "https://github.com/protocollar/fr8/releases/download/v#{version}/fr8_#{version}_darwin_amd64.tar.gz"
      sha256 "7c8a4198224852709d4b963126eea371b17a823055916760f9059b581ca3cfdc"
    end
    on_arm do
      url "https://github.com/protocollar/fr8/releases/download/v#{version}/fr8_#{version}_darwin_arm64.tar.gz"
      sha256 "dfe2c5d7079bd816881ec49dae371f25e197616626d3a30918dd85053868e3cd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/protocollar/fr8/releases/download/v#{version}/fr8_#{version}_linux_amd64.tar.gz"
      sha256 "a4179c05f4103e1a28661feaef1df24d007e1862eae3e97862717f6f50cd4612"
    end
    on_arm do
      url "https://github.com/protocollar/fr8/releases/download/v#{version}/fr8_#{version}_linux_arm64.tar.gz"
      sha256 "4b7e3e3bf8acda1598655ccaf27d56fd9ef3fde324f4a855eaa3f6586e507f7f"
    end
  end

  # No zap stanza required
end
