# This file was generated by GoReleaser. DO NOT EDIT.
cask "fr8" do
  name "fr8"
  desc "Manage git worktrees as isolated dev workspaces"
  homepage "https://github.com/protocollar/fr8"
  version "0.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fr8"

  on_macos do
    on_intel do
      url "https://github.com/protocollar/fr8/releases/download/v#{version}/fr8_#{version}_darwin_amd64.tar.gz"
      sha256 "46c8e65206d15beb29a86375536185ef491956bf5f228fe5f823e3d856682c0e"
    end
    on_arm do
      url "https://github.com/protocollar/fr8/releases/download/v#{version}/fr8_#{version}_darwin_arm64.tar.gz"
      sha256 "28386d7fb5e58e0b702c25d2d81594e252a70a4eed569098239bb5badb93e1cc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/protocollar/fr8/releases/download/v#{version}/fr8_#{version}_linux_amd64.tar.gz"
      sha256 "20c8cdd4e8b872ea258f76e970b2895a64378c12a1b907889d10055781538620"
    end
    on_arm do
      url "https://github.com/protocollar/fr8/releases/download/v#{version}/fr8_#{version}_linux_arm64.tar.gz"
      sha256 "4d0799bdc2afae535cf30e79c8a72d404810acbc46352394cc811d63d53599ab"
    end
  end

  # No zap stanza required
end
