# This file was generated by GoReleaser. DO NOT EDIT.
cask "fr8" do
  name "fr8"
  desc "Manage git worktrees as isolated dev workspaces"
  homepage "https://github.com/protocollar/fr8"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fr8"

  on_macos do
    on_intel do
      url "https://github.com/protocollar/fr8/releases/download/v#{version}/fr8_#{version}_darwin_amd64.tar.gz"
      sha256 "bb6434cde45ec18e418d54ff927722be5131441f85df9a6da17dfce07f62e65a"
    end
    on_arm do
      url "https://github.com/protocollar/fr8/releases/download/v#{version}/fr8_#{version}_darwin_arm64.tar.gz"
      sha256 "73277a1ca4365bdd3fee50951bbb4eb474e2769d7e76b54b395d63b4af20eaa2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/protocollar/fr8/releases/download/v#{version}/fr8_#{version}_linux_amd64.tar.gz"
      sha256 "54552b96f3ab9d8c4bcc76b993c83c11faed6d7e9501f7fe3d95f9e8395005bc"
    end
    on_arm do
      url "https://github.com/protocollar/fr8/releases/download/v#{version}/fr8_#{version}_linux_arm64.tar.gz"
      sha256 "dffbc3c9b9b538e7909296cbafcb2c6002cbe2c90356e8982cb289ab8df195ab"
    end
  end

  # No zap stanza required
end
